[info]
settings_tag=Whisper and Vosk server settings
[server]
host=0.0.0.0
port=20741
cors_origins=*
log_level=warning
socket_heartbeat_s = 10
socket_timeout_s = 15
[users]
common_auth_token=test1234
user1=user001
token1=ecd71870d1963316a97e3ac3408c9835ad8cf0f3c1bc703527c30265534f75ae
# add more users in tuples: user2=..., token2=..., ...
[app]
recordings_path=../recordings/
# engines: vosk, coqui, whisper, dynamic (all), wave_file_writer, test
asr_engine=dynamic
[asr_models]
base_folder=../models/
# Model 1
path1=vosk-model-small-de
lang1=de-DE
engine1=vosk
task1=assistant
# Model 2
path2=vosk-model-small-en-us
lang2=en-US
engine2=vosk
task2=assistant
# Model 3
path3=whisper-tiny-ct2-int8
lang3=en-US
engine3=whisper
task3=conversation
name3=whisper-tiny-en
# Model 4
path4=whisper-tiny-ct2-int8
lang4=de-DE
engine4=whisper
task4=conversation
name4=whisper-tiny-de
# Model 5 - Example
#path5=sepia-kalid-custom-de
#lang5=de-DE
#engine5=vosk
#task5=assistant
#name5=sepia-assistant-de
# Model 6
#path6=whisper-large-v3-turbo-ct2
#lang6=en-US
#engine6=whisper
#task6=conversation
#name6=whisper-large-en
#beamsize6=1
#prompt6=You are the SEPIA voice assistant. You activation word is hey SEPIA.
#translate6=false
#compute_device6=cuda
#cuda_win_path6=C:\my-libs\cuda
#compute_type6=int8
#
# add more models by increasing the index and add properties:
# path{index}=..., lang{index}=..., {prop1}{index}=..., ...
[speaker_models]
base_folder=../models/
path1=vosk-model-spk
[whisper]
threads_per_model=2
model_cache_size=2
cache_expire_time_s=120
